apiVersion: v2
name: restheart
description: A Helm chart for RESTHeart, a Java backend framework for REST, GraphQL, and WebSocket APIs with MongoDB.
type: application
version: 9.7.0
appVersion: "9.7.0"

home: https://restheart.org
sources:
  - https://github.com/SoftInstigate/restheart
maintainers:
  - name: SoftInstigate
    url: https://softinstigate.com
keywords:
  - rest
  - mongodb
  - api
  - graphql
  - websocket
  - java
  - backend
