FROM gcr.io/distroless/java:11

LABEL maintainer="SoftInstigate <info@softinstigate.com>"

WORKDIR /opt/restheart-platform
COPY Docker/etc/restheart-platform-core.yml etc/
COPY Docker/etc/core.properties etc/
COPY restheart-platform-core.jar restheart-platform-core.jar

ENTRYPOINT [ "java", "-Dfile.encoding=UTF-8", "-server", "-jar", "restheart-platform-core.jar", "etc/restheart-platform-core.yml"]
CMD ["--envFile", "etc/core.properties"]

EXPOSE 8080
