FROM gcr.io/distroless/java:11

LABEL maintainer="SoftInstigate <info@softinstigate.com>"

WORKDIR /opt/restheart-platform
COPY Docker/etc/acl.yml etc/
COPY Docker/etc/restheart-platform-security.yml etc/
COPY Docker/etc/users.yml etc/
COPY Docker/etc/security.properties etc/
COPY restheart-platform-security.jar restheart-platform-security.jar

ENTRYPOINT [ "java", "-Dfile.encoding=UTF-8", "-server", "-jar", "restheart-platform-security.jar", "etc/restheart-platform-security.yml"]
CMD ["--envFile", "etc/security.properties"]
EXPOSE 8080 4443
