apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restheart.fullname" . }}
  labels:
    {{- include "restheart.labels" . | nindent 4 }}
data:
  restheart.yml: {{ .Values.restHeartConfiguration | toYaml | b64enc }}