# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "dummy"
  config.vm.synced_folder "..", "/restheart"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  #This might be handy in case of aws provider, where host name is stored in ssh_info hash of each machine
  #config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
  #  if hostname = (vm.ssh_info && vm.ssh_info[:host])
  #    `host #{hostname}`.split("\n").last[/(\d+\.\d+\.\d+\.\d+)/, 1]
  #  end
  #end
    
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAJAN46ZEXWGG6VIXA"
    aws.secret_access_key = "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"
    aws.region = "eu-west-1"
    aws.keypair_name = "uji"
    aws.instance_type = "t2.micro"
    aws.ami = "ami-afcf19d8" # Ubuntu 12.04.4 LTS (Precise Pangolin) [20140717] HVM

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/uji/development/amazon ec2/uji.pem"
  end

  config.vm.provider "virtualbox" do |vb, override|
    override.vm.box = "hashicorp/precise64"
    vb.memory = 512
    vb.cpus = 4
  end

  config.omnibus.chef_version = :latest

  config.vm.define "mongodb" do |db|
    db.vm.hostname = 'mongo-node'
    db.vm.network "private_network", ip: "192.168.50.2"
    db.vm.network "forwarded_port", guest: 27017, host: 27017
    db.vm.network "forwarded_port", guest: 28017, host: 28017
    db.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "./chef/cookbooks"
      chef.roles_path = "./chef/roles"
      chef.data_bags_path = "./chef/data_bags"
      chef.add_role "mongodb-node"
    end
  end

  config.vm.define "restheart-1" do |rh|
    rh.vm.hostname = 'restheart-node-1'
    rh.vm.network "private_network", ip: "192.168.50.3"
    rh.vm.network "forwarded_port", guest: 8080, host: 8080
    rh.vm.network "forwarded_port", guest: 4443, host: 4443
    rh.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "./chef/cookbooks"
      chef.roles_path = "./chef/roles"
      chef.data_bags_path = "./chef/data_bags"
      chef.add_role "restheart-node"
    end
  end


  #config.vm.define "restheart-2" do |rh|
  #  rh.vm.hostname = 'restheart-node-2'
  #  rh.vm.network "private_network", ip: "192.168.50.4"
  #  rh.vm.network "forwarded_port", guest: 8080, host: 9080
  #  rh.vm.network "forwarded_port", guest: 4443, host: 5443
  #  rh.vm.provision "chef_solo" do |chef|
  #    chef.cookbooks_path = "./chef/cookbooks"
  #    chef.roles_path = "./chef/roles"
  #    chef.data_bags_path = "./chef/data_bags"
  #    chef.add_role "restheart-node"
  #  end
  # end

end