/*-
 * ========================LICENSE_START=================================
 * restheart-core
 * %%
 * Copyright (C) 2014 - 2020 SoftInstigate
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =========================LICENSE_END==================================
 */
package org.restheart;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.LoggerContext;
import com.google.common.collect.Maps;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.regex.Pattern;


import org.restheart.utils.URLUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.SafeConstructor;

import static org.restheart.ConfigurationKeys.*;
import static org.restheart.ConfigurationUtils.*;

/**
 * Class that holds the configuration.
 *
 * @author Andrea Di Cesare {@literal <andrea@softinstigate.com>}
 */
public class Configuration {

    /**
     * the version is read from the JAR's MANIFEST.MF file, which is automatically
     * generated by the Maven build process
     */
    public static final String VERSION = Configuration.class.getPackage().getImplementationVersion() == null
            ? "unknown, not packaged"
            : Configuration.class.getPackage().getImplementationVersion();

    private static final Logger LOGGER = LoggerFactory.getLogger(Configuration.class);

    public static final String DEFAULT_ROUTE = "0.0.0.0";

    /**
     * hold the path of the configuration file
     */
    private static Path PATH = null;

    private final boolean httpsListener;
    private final int httpsPort;
    private final String httpsHost;
    private final boolean httpListener;
    private final int httpPort;
    private final String httpHost;
    private final boolean ajpListener;
    private final int ajpPort;
    private final String ajpHost;
    private final String instanceName;
    private final String pluginsDirectory;
    private final String keystoreFile;
    private final String keystorePassword;
    private final String certPassword;
    private final List<Map<String, Object>> proxies;
    private final List<Map<String, Object>> staticResourcesMounts;
    private final Map<String, Map<String, Object>> pluginsArgs;
    private final Map<String, Map<String, Object>> authMechanisms;
    private final Map<String, Map<String, Object>> authenticators;
    private final Map<String, Map<String, Object>> authorizers;
    private final Map<String, Map<String, Object>> tokenManagers;
    private final String logFilePath;
    private final Level logLevel;
    private final boolean logToConsole;
    private final boolean logToFile;
    private final List<String> traceHeaders;
    private final int requestsLimit;
    private final int ioThreads;
    private final int workerThreads;
    private final int bufferSize;
    private final boolean directBuffers;
    private final boolean forceGzipEncoding;
    private final Map<String, Object> connectionOptions;
    private final Integer logExchangeDump;
    private final boolean ansiConsole;
    private final boolean allowUnescapedCharactersInUrl;

    private Map<String, Object> conf;

    /**
     * Creates a new instance of Configuration with defaults values.
     */
    public Configuration() {
        this(null, DefaultConfiguration.get(), true);
    }

    /**
     * Creates a new instance of Configuration from the configuration file For any
     * missing property the default value is used.
     *
     * @param confFilePath the path of the configuration file
     * @throws org.restheart.ConfigurationException
     */
    public Configuration(final Path confFilePath) throws ConfigurationException {
        this(confFilePath, false);
    }

    /**
     * Creates a new instance of Configuration from the configuration file For any
     * missing property the default value is used.
     *
     * @param confFilePath the path of the configuration file
     * @param silent
     * @throws org.restheart.ConfigurationException
     */
    public Configuration(final Path confFilePath, boolean silent) throws ConfigurationException {
        this(confFilePath, fromFile(confFilePath), silent);
    }

    /**
     * Creates a new instance of Configuration from the configuration file For any
     * missing property the default value is used.
     *
     * @param conf   the key-value configuration map
     * @param silent
     * @throws org.restheart.ConfigurationException
     */
    @SuppressWarnings({ "deprecation" })
    public Configuration(final Path confFilePath, Map<String, Object> conf, boolean silent) throws ConfigurationException {
        PATH = confFilePath;

        this.conf = conf;

        // check if service configuration follows old (<2.0)format
        if (conf.get(SERVICES_KEY) != null) {
            LOGGER.error("The services configuration section is obsolete.");
            throw new ConfigurationException("Wrong Services configuration");
        }

        ansiConsole = asBoolean(conf, ANSI_CONSOLE_KEY, true, silent);

        httpsListener = asBoolean(conf, HTTPS_LISTENER_KEY, true, silent);
        httpsPort = asInteger(conf, HTTPS_PORT_KEY, DEFAULT_HTTPS_PORT, silent);
        httpsHost = asString(conf, HTTPS_HOST_KEY, DEFAULT_HTTPS_HOST, silent);

        httpListener = asBoolean(conf, HTTP_LISTENER_KEY, false, silent);
        httpPort = asInteger(conf, HTTP_PORT_KEY, DEFAULT_HTTP_PORT, silent);
        httpHost = asString(conf, HTTP_HOST_KEY, DEFAULT_HTTP_HOST, silent);

        ajpListener = asBoolean(conf, AJP_LISTENER_KEY, DEFAULT_AJP_LISTENER, silent);
        ajpPort = asInteger(conf, AJP_PORT_KEY, DEFAULT_AJP_PORT, silent);
        ajpHost = asString(conf, AJP_HOST_KEY, DEFAULT_AJP_HOST, silent);

        instanceName = asString(conf, INSTANCE_NAME_KEY, DEFAULT_INSTANCE_NAME, silent);
        keystoreFile = asString(conf, KEYSTORE_FILE_KEY, null, silent);
        keystorePassword = asString(conf, KEYSTORE_PASSWORD_KEY, null, silent);
        certPassword = asString(conf, CERT_PASSWORD_KEY, null, silent);

        proxies = asListOfMaps(conf, PROXY_KEY, new ArrayList<>(), silent);

        staticResourcesMounts = asListOfMaps(conf, STATIC_RESOURCES_MOUNTS_KEY, new ArrayList<>(), silent);

        pluginsDirectory = asString(conf, PLUGINS_DIRECTORY_PATH_KEY, null, silent);

        pluginsArgs = asMapOfMaps(conf, PLUGINS_ARGS_KEY, new LinkedHashMap<>(), silent);

        authMechanisms = asMapOfMaps(conf, AUTH_MECHANISMS_KEY, new LinkedHashMap<>(), silent);

        authenticators = asMapOfMaps(conf, AUTHENTICATORS_KEY, new LinkedHashMap<>(), silent);

        authorizers = asMapOfMaps(conf, AUTHORIZERS_KEY, new LinkedHashMap<>(), silent);

        tokenManagers = asMapOfMaps(conf, TOKEN_MANAGER_KEY, new LinkedHashMap<>(), silent);

        logFilePath = asString(conf, LOG_FILE_PATH_KEY, URLUtils.removeTrailingSlashes(System.getProperty("java.io.tmpdir")).concat(File.separator + "restheart.log"), silent);
        String _logLevel = asString(conf, LOG_LEVEL_KEY, "INFO", silent);
        logToConsole = asBoolean(conf, ENABLE_LOG_CONSOLE_KEY, true, silent);
        logToFile = asBoolean(conf, ENABLE_LOG_FILE_KEY, true, silent);

        Level level;
        try {
            level = Level.valueOf(_logLevel);
        } catch (Exception e) {
            if (!silent) {
                LOGGER.info("wrong value for parameter {}: {}, using its default value {}", "log-level", _logLevel,
                        "INFO");
            }
            level = Level.INFO;
        }

        logLevel = level;

        traceHeaders = asListOfStrings(conf, REQUESTS_LOG_TRACE_HEADERS_KEY, Collections.emptyList(), silent);

        requestsLimit = asInteger(conf, REQUESTS_LIMIT_KEY, 100, silent);
        ioThreads = asInteger(conf, IO_THREADS_KEY, 2, silent);
        workerThreads = asInteger(conf, WORKER_THREADS_KEY, 32, silent);
        bufferSize = asInteger(conf, BUFFER_SIZE_KEY, 16384, silent);
        directBuffers = asBoolean(conf, DIRECT_BUFFERS_KEY, true, silent);
        forceGzipEncoding = asBoolean(conf, FORCE_GZIP_ENCODING_KEY, false, silent);
        logExchangeDump = asInteger(conf, LOG_REQUESTS_LEVEL_KEY, 0, silent);
        connectionOptions = asMap(conf, CONNECTION_OPTIONS_KEY, silent);
        allowUnescapedCharactersInUrl = asBoolean(conf, ALLOW_UNESCAPED_CHARACTERS_IN_URL, true, silent);
    }

    @Override
    public String toString() {
        return "Configuration{" + "instanceName=" + instanceName + ", configurationFilePath="
                + PATH + ", httpsListener=" + httpsListener + ", httpsPort=" + httpsPort + ", httpsHost=" + httpsHost
                + ", httpListener=" + httpListener + ", httpPort=" + httpPort + ", httpHost=" + httpHost
                + ", ajpListener=" + ajpListener + ", ajpPort=" + ajpPort + ", ajpHost=" + ajpHost
                + ", pluginsDirectory=" + pluginsDirectory + ", keystoreFile=" + keystoreFile + ", keystorePassword="
                + keystorePassword + ", certPassword=" + certPassword + ", proxies=" + proxies + ", pluginsArgs="
                + pluginsArgs + ", authMechanisms=" + authMechanisms + ", authenticators=" + authenticators
                + ", authorizers=" + authorizers + ", tokenManager=" + tokenManagers + ", logFilePath=" + logFilePath
                + ", logLevel=" + logLevel + ", logToConsole=" + logToConsole + ", logToFile=" + logToFile
                + ", traceHeaders=" + traceHeaders + ", requestsLimit=" + requestsLimit + ", ioThreads=" + ioThreads
                + ", workerThreads=" + workerThreads + ", bufferSize=" + bufferSize + ", directBuffers=" + directBuffers
                + ", forceGzipEncoding=" + forceGzipEncoding + ", connectionOptions=" + connectionOptions
                + ", logExchangeDump=" + logExchangeDump + ", ansiConsole=" + ansiConsole
                + ", allowUnescapedCharactersInUrl=" + allowUnescapedCharactersInUrl + '}';
    }

    public Map<String, Object> toMap() {
        return Collections.unmodifiableMap(this.conf);
    }

    /**
     * @return the proxies
     */
    public List<Map<String, Object>> getProxies() {
        return Collections.unmodifiableList(proxies);
    }

    /**
     * @return the staticResourcesMounts
     */
    public List<Map<String, Object>> getStaticResourcesMounts() {
        return Collections.unmodifiableList(staticResourcesMounts);
    }

    /**
     *
     * @return true if the Ansi console is enabled
     */
    public boolean isAnsiConsole() {
        return ansiConsole;
    }

    /**
     * @return the httpsListener
     */
    public boolean isHttpsListener() {
        return httpsListener;
    }

    /**
     * @return the httpsPort
     */
    public int getHttpsPort() {
        return httpsPort;
    }

    /**
     * @return the httpsHost
     */
    public String getHttpsHost() {
        return httpsHost;
    }

    /**
     * @return the httpListener
     */
    public boolean isHttpListener() {
        return httpListener;
    }

    /**
     * @return the httpPort
     */
    public int getHttpPort() {
        return httpPort;
    }

    /**
     * @return the httpHost
     */
    public String getHttpHost() {
        return httpHost;
    }

    /**
     * @return the ajpListener
     */
    public boolean isAjpListener() {
        return ajpListener;
    }

    /**
     * @return the ajpPort
     */
    public int getAjpPort() {
        return ajpPort;
    }

    /**
     * @return the ajpHost
     */
    public String getAjpHost() {
        return ajpHost;
    }

    /**
     * @return the pluginsDirectory
     */
    public String getPluginsDirectory() {
        return this.pluginsDirectory;
    }

    /**
     * @return the keystoreFile
     */
    public String getKeystoreFile() {
        return keystoreFile;
    }

    /**
     * @return the keystorePassword
     */
    public String getKeystorePassword() {
        return keystorePassword;
    }

    /**
     * @return the certPassword
     */
    public String getCertPassword() {
        return certPassword;
    }

    /**
     * @return the logFilePath
     */
    public String getLogFilePath() {
        return logFilePath;
    }

    /**
     * @return the logLevel
     */
    public Level getLogLevel() {
        var logbackConfigurationFile = System.getProperty("logback.configurationFile");
        if (logbackConfigurationFile != null && !logbackConfigurationFile.isEmpty()) {
            var loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
            var logger = loggerContext.getLogger("org.restheart.security");
            return logger.getLevel();
        }

        return logLevel;
    }

    /**
     * @return the logToConsole
     */
    public boolean isLogToConsole() {
        return logToConsole;
    }

    /**
     * @return the logToFile
     */
    public boolean isLogToFile() {
        return logToFile;
    }

    public List<String> getTraceHeaders() {
        return Collections.unmodifiableList(traceHeaders);
    }

    /**
     * @return the ioThreads
     */
    public int getIoThreads() {
        return ioThreads;
    }

    /**
     * @return the workerThreads
     */
    public int getWorkerThreads() {
        return workerThreads;
    }

    /**
     * @return the bufferSize
     */
    public int getBufferSize() {
        return bufferSize;
    }

    /**
     * @return the directBuffers
     */
    public boolean isDirectBuffers() {
        return directBuffers;
    }

    /**
     * @return the forceGzipEncoding
     */
    public boolean isForceGzipEncoding() {
        return forceGzipEncoding;
    }

    /**
     * @return the pluginsArgs
     */
    public Map<String, Map<String, Object>> getPluginsArgs() {
        return Collections.unmodifiableMap(pluginsArgs);
    }

    /**
     * @return the authMechanisms
     */
    public Map<String, Map<String, Object>> getAuthMechanisms() {
        return Collections.unmodifiableMap(authMechanisms);
    }

    /**
     * @return the authenticators
     */
    public Map<String, Map<String, Object>> getAuthenticators() {
        return Collections.unmodifiableMap(authenticators);
    }

    /**
     * @return the authorizers
     */
    public Map<String, Map<String, Object>> getAuthorizers() {
        return Collections.unmodifiableMap(authorizers);
    }

    /**
     * @return the requestsLimit
     */
    public int getRequestsLimit() {
        return requestsLimit;
    }

    /**
     * @return the tokenManagers
     */
    public Map<String, Map<String, Object>> getTokenManagers() {
        return Collections.unmodifiableMap(tokenManagers);
    }

    /**
     *
     * @return the logExchangeDump Boolean
     */
    public Integer logExchangeDump() {
        return logExchangeDump;
    }

    /**
     * @return the connectionOptions
     */
    public Map<String, Object> getConnectionOptions() {
        return Collections.unmodifiableMap(connectionOptions);
    }

    /**
     * @return the instanceName
     */
    public String getInstanceName() {
        return instanceName;
    }

    public boolean isAllowUnescapedCharactersInUrl() {
        return allowUnescapedCharactersInUrl;
    }

    /**
     *
     * @return the path of the configuration file
     */
    public static Path getPath() {
        return PATH;
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> fromFile(final Path confFilePath) throws ConfigurationException {
        var yaml = new Yaml(new SafeConstructor());
        Map<String, Object> conf = null;

        try (FileInputStream fis = new FileInputStream(confFilePath.toFile())) {
            conf = (Map<String, Object>) yaml.load(fis);
        } catch (FileNotFoundException fne) {
            throw new ConfigurationException("Configuration file not found", fne);
        } catch (Throwable t) {
            throw new ConfigurationException("Error parsing the configuration file", t);
        }

        return conf;
    }

    static boolean isParametric(final Path confFilePath) throws IOException {
        try (var sc = new Scanner(confFilePath, "UTF-8")) {
            return sc.findAll(Pattern.compile("\\{\\{.*\\}\\}")).limit(1).count() > 0;
        }
    }
}

class DefaultConfiguration {
    private static Map<String, Object> DEFAULT_CONFIGURATION = new HashMap<>();

    static {
        DEFAULT_CONFIGURATION.put(ANSI_CONSOLE_KEY, true);

        DEFAULT_CONFIGURATION.put(HTTPS_LISTENER_KEY, DEFAULT_HTTPS_LISTENER);
        DEFAULT_CONFIGURATION.put(HTTPS_PORT_KEY, DEFAULT_HTTPS_PORT);
        DEFAULT_CONFIGURATION.put(HTTPS_HOST_KEY, DEFAULT_HTTPS_HOST);

        DEFAULT_CONFIGURATION.put(HTTP_LISTENER_KEY, DEFAULT_HTTP_LISTENER);
        DEFAULT_CONFIGURATION.put(HTTP_PORT_KEY, DEFAULT_HTTP_PORT);
        DEFAULT_CONFIGURATION.put(HTTP_HOST_KEY, DEFAULT_HTTP_HOST);

        DEFAULT_CONFIGURATION.put(AJP_LISTENER_KEY, DEFAULT_AJP_LISTENER);
        DEFAULT_CONFIGURATION.put(AJP_PORT_KEY, DEFAULT_AJP_PORT);
        DEFAULT_CONFIGURATION.put(AJP_HOST_KEY, DEFAULT_AJP_HOST);

        DEFAULT_CONFIGURATION.put(INSTANCE_NAME_KEY, DEFAULT_INSTANCE_NAME);

        DEFAULT_CONFIGURATION.put(KEYSTORE_FILE_KEY, null);
        DEFAULT_CONFIGURATION.put(KEYSTORE_PASSWORD_KEY, null);
        DEFAULT_CONFIGURATION.put(CERT_PASSWORD_KEY, null);

        DEFAULT_CONFIGURATION.put(ANSI_CONSOLE_KEY, new ArrayList<>());

        DEFAULT_CONFIGURATION.put(PROXY_KEY, new LinkedHashMap<>());

        DEFAULT_CONFIGURATION.put(PLUGINS_DIRECTORY_PATH_KEY, "plugins");

        DEFAULT_CONFIGURATION.put(PLUGINS_ARGS_KEY, new LinkedHashMap<>());

        DEFAULT_CONFIGURATION.put(AUTH_MECHANISMS_KEY, new LinkedHashMap<>());
        DEFAULT_CONFIGURATION.put(AUTHENTICATORS_KEY, new LinkedHashMap<>());
        DEFAULT_CONFIGURATION.put(AUTHORIZERS_KEY, null);
        DEFAULT_CONFIGURATION.put(TOKEN_MANAGER_KEY, URLUtils.removeTrailingSlashes(System.getProperty("java.io.tmpdir")).concat(File.separator + "restheart.log"));

        DEFAULT_CONFIGURATION.put(LOG_FILE_PATH_KEY, new LinkedHashMap<>());
        DEFAULT_CONFIGURATION.put(ENABLE_LOG_CONSOLE_KEY, true);
        DEFAULT_CONFIGURATION.put(ENABLE_LOG_FILE_KEY, true);
        DEFAULT_CONFIGURATION.put(LOG_LEVEL_KEY, Level.INFO);
        DEFAULT_CONFIGURATION.put(ConfigurationKeys.REQUESTS_LOG_LEVEL_KEY, 0);

        DEFAULT_CONFIGURATION.put(REQUESTS_LOG_TRACE_HEADERS_KEY, Collections.emptyList());

        DEFAULT_CONFIGURATION.put(REQUESTS_LIMIT_KEY, 100);
        DEFAULT_CONFIGURATION.put(IO_THREADS_KEY, 2);
        DEFAULT_CONFIGURATION.put(WORKER_THREADS_KEY, 32);
        DEFAULT_CONFIGURATION.put(BUFFER_SIZE_KEY, 16384);
        DEFAULT_CONFIGURATION.put(DIRECT_BUFFERS_KEY, true);
        DEFAULT_CONFIGURATION.put(FORCE_GZIP_ENCODING_KEY, false);
        DEFAULT_CONFIGURATION.put(CONNECTION_OPTIONS_KEY, Maps.newHashMap());
        DEFAULT_CONFIGURATION.put(ALLOW_UNESCAPED_CHARACTERS_IN_URL, true);
    }

    static Map<String, Object> get() {
        return DEFAULT_CONFIGURATION;
    }
}