FROM debian:buster-slim

LABEL maintainer="SoftInstigate <info@softinstigate.com>"

WORKDIR /opt/restheart
COPY target/restheart .
COPY etc/restheart.yml etc/default.properties etc/
RUN mkdir plugins

ENV MONGO_URI="mongodb://host.docker.internal"
ENTRYPOINT [ "./restheart", "-Dfile.encoding=UTF-8", "etc/restheart.yml" ]
CMD ["--envFile", "etc/default.properties"]
EXPOSE 8009 8080 4443